### ISSUE TITLE
Pull Request 1 Feedback

### ISSUE THREAD

**Issue by brandonbrown** [mattdevio/moolahlah#4]
In reference to #1 

Looks like your project bootstrap works well. A few items for you to review:

- [x] Can you explain why you're using `.pug` templating over other options?
- [x] Please add to your main `.README` instructions to run your app on a local machine. 
- [x] Project Milestones Link is broken. [Click here.](https://github.com/mattdevio/moolahlah/blob/master/docs/PROJECT_MILESTONES)
- [x] Currently not a problem as it was most likely done for testing and fast integration purposes, but be sure to consider making components such as `<Logo />` reusable and not stuck within other files.
- [x] Move away from hard set pixel widths as soon as possible. Recommend a combination of Flex and Grid for layout and positioning purposes.
- [x] Be sure to have fallbacks for fonts, especially for any display or heavily stylized styles
- [x] Why are you not utilizing Google font's servers?

There may be more to come as other contributors are added to the project.

**Comment by mattdevio** [comment]
1. Why are you using pug? 
Answer: I have been using pug since before it was re-named from jade. It was the first server side template engine I used, and I am familiar with it. It is also on the recommended list for integration with the express framework.  I have used mustache, ejs, underscore and even written my own in other projects; however, for ease of use I think I will stick with it. I am not really using it for its full potential right now, but when I get into server side rendering my initial React load, it will come in handy.

**Comment by mattdevio** [comment]
**2. Add Instructions to README.md**
**Answer:** Completed and pending merge approval of branch `GettingStartedReadme`.

**Comment by mattdevio** [comment]
**3. Project Milestones Link Broken**
**Answer:** Completed and pending merge approval of branch `GettingStartedReadme`.

**Comment by mattdevio** [comment]
**4. Components in `entry.jsx` file**
**Answer:** This was totally just done for testing. I will build out the client structure as needed.

**Comment by mattdevio** [comment]
**5. Pixel units in CSS**
**Answer:** I will use 'ems' when i start normal development. Once again, just for testing / hacking.

**Comment by mattdevio** [comment]
**6. Fallback fonts**
**Answer:** I will add some browser save fallbacks when I get started.

**Comment by mattdevio** [comment]
**7. CDN Fonts**
**Answer:** I just wanted to see if I could. I will probably go back to using the Google Host. I didn't realize that google font api sends back dynamic style sheets based on browser / OS that requested it.
